[package]
name = "kapun-presentation-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "kapun_presentation_rust"

[dependencies]
uniffi.workspace = true

[target.'cfg(target_arch = "arm")'.dependencies]
kapun-util-rust = { path = "../../kapun-util/rust" }
