[package]
name = "kapun-x509"
version = "0.1.0"
edition = "2024"

[dependencies]
x509-parser = { version = "0.16.0", features = ["validate"] }
ureq = { workspace = true, optional = true }
whitespace-sifter = "2.3.7"
tracing = "^0.1"
kapun-crypto-provider = { path = "../../kapun-crypto-provider", default-features = false }
simple_x509 = { version = "1.1.0"}
rand.workspace = true
p12 = { git = "https://github.com/heidiverse/p12.git", optional = true}
x509-cert = { version = "0.3.0", features = ["builder"], optional = true }
signature = "3.0.0"
sha2.workspace = true


[features]
default = ["crl", "builder"]
uniffi = []
crl = ["dep:ureq"]
builder = ["p12", "x509-cert"]
p12 = ["dep:p12"]


[dev-dependencies]
flate2 = "1.1.9"
tar = "0.4.45"
pem = "3.0.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
josekit = { git = "https://github.com/heidiverse/josekit-rs.git", default-features = false, features = [
    "rustcrypto",
    "pqc",
    "legacy-crypto",
    "kapun-provider"
]}
base64.workspace = true
