kotlin.code.style=official
ARTIFACT_ID=kapun-dcql-mdoc
POM_NAME=kapun-dcql-mdoc
POM_DESCRIPTION=Kapun DCQL support for ISO mdoc credentials
GROUP=org.kapunsdk
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/KapunSDK/kapun-sdk
POM_SCM_URL=https://github.com/KapunSDK/kapun-sdk
POM_SCM_CONNECTION=scm:git@github.com:KapunSDK/kapun-sdk.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:KapunSDK/kapun-sdk.git
POM_LICENCE_NAME=License
POM_LICENCE_URL=https://github.com/KapunSDK/kapun-sdk/blob/main/LICENSE
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=UbiqueInnovation
POM_DEVELOPER_NAME=Ubique Innovation
POM_DEVELOPER_URL=https://www.ubique.ch/
SONATYPE_STAGING_PROFILE=org.kapunsdk

